name: Bug Report
description: Report a bug in the JointProject to help us improve.
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug. Please fill in as much information as possible to help us quickly identify and fix the issue.

  - type: textarea
    id: bug_description
    attributes:
      label: Detailed Description
      description: A detailed description of the bug, including steps to reproduce, expected outcome, and actual outcome.
      placeholder: "Steps to reproduce, expected outcome, and actual outcome."
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Affected Version
      description: The version of the project in which the bug occurs.
      placeholder: "e.g., 1.2.3"
    validations:
      required: false

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is the bug?
      options:
        - Critical
        - Major
        - Minor
        - Cosmetic
    validations:
      required: true
