blank_issues_enabled: false
issue_templates:
  - name: Bug report
    description: File a bug report
    labels: [bug]
    title: "[BUG] "
  - name: Feature request
    description: Request a new feature
    labels: [feature]
    title: "[FEATURE] "