name: Conventional Commits Changelog

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install standard-version
        run: npm install -g standard-version

      - name: Generate Changelog and Create Release
        run: |
          standard-version --release-as minor
          git push --follow-tags origin main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
