name: Conventional Commits Changelog

on:
  pull_request:
    branches: [ main, development ]
  push:
    branches: [ main, development ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install standard-version
        run: npm install -g standard-version

      - name: Configure Git
        run: |
          git config --global user.email "changelog.bot@gamemanagement.com"
          git config --global user.name "GAME Management Bot"

      - name: Generate Changelog and Create Release
        run: |
          standard-version --release-as minor
          git push --follow-tags origin ${{ github.ref_name }}
        env:
          GH_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
